// List of cuisine options for restaurant selection
export const cuisineOptions = [
  { id: "african", label: "African" },
  { id: "american", label: "American" },
  { id: "bbq", label: "BBQ" },
  { id: "breakfast", label: "Breakfast" },
  { id: "british", label: "British" },
  { id: "cafe", label: "Cafe" },
  { id: "caribbean", label: "Caribbean" },
  { id: "chinese", label: "Chinese" },
  { id: "dessert", label: "Dessert" },
  { id: "european", label: "European" },
  { id: "fastfood", label: "Fast Food" },
  { id: "french", label: "French" },
  { id: "greek", label: "Greek" },
  { id: "healthyfood", label: "Healthy Food" },
  { id: "indian", label: "Indian" },
  { id: "indonesian", label: "Indonesian" },
  { id: "irish", label: "Irish" },
  { id: "italian", label: "Italian" },
  { id: "japanese", label: "Japanese" },
  { id: "korean", label: "Korean" },
  { id: "lebanese", label: "Lebanese" },
  { id: "mediterranean", label: "Mediterranean" },
  { id: "mexican", label: "Mexican" },
  { id: "middleeastern", label: "Middle Eastern" },
  { id: "moroccan", label: "Moroccan" },
  { id: "pizza", label: "Pizza" },
  { id: "seafood", label: "Seafood" },
  { id: "spanish", label: "Spanish" },
  { id: "steakhouse", label: "Steakhouse" },
  { id: "sushi", label: "Sushi" },
  { id: "thai", label: "Thai" },
  { id: "turkish", label: "Turkish" },
  { id: "vegan", label: "Vegan" },
  { id: "vegetarian", label: "Vegetarian" },
  { id: "vietnamese", label: "Vietnamese" },
];